version: "3.8"
services:
  rctf:
    image: ghcr.io/minpeter/rctf:master
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PORT=80
    volumes:
      - ./conf.d:/app/conf.d
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.rctf.rule=Host(`rctf.minpeter.tech`)
networks:
  traefik:
    external: true
