version: "3.8"
services:
  traefik:
    image: traefik
    container_name: traefik
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.minpeter.tech`) && PathPrefix(`/api`, `/dashboard`)
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.tls.certresolver=myresolver
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.middlewares=traefik-auth
      - traefik.http.middlewares.traefik-auth.basicauth.usersfile=/usersfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yaml:/etc/traefik/traefik.yaml
      - ./external_services:/external_services
      - ./usersfile:/usersfile
      - traefik-letsencrypt:/letsencrypt
    extra_hosts:
      - host.docker.internal:host-gateway

  dockge:
    image: louislam/dockge
    container_name: dockge
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - dockge:/app/data
      - ./stacks:/stacks
    environment:
      # Tell Dockge where is your stacks directory
      - DOCKGE_STACKS_DIR=/stacks
    labels:
      - traefik.enable=true
      - traefik.http.services.dockge.loadbalancer.server.port=5001
      - traefik.http.routers.dockge.entrypoints=websecure
      - traefik.http.routers.dockge.tls.certresolver=myresolver
      - traefik.http.routers.dockge.rule=Host(`dockge.minpeter.tech`)

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: --interval 30

networks:
  default:
    name: traefik

volumes:
  traefik-letsencrypt:
  dockge:
