version: "3.8"
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx.rule=Host(`nginx.minpeter.tech`,
        `ctf.hansei.kr`)
      - traefik.http.routers.nginx.tls.certresolver=http-resolver

    networks:
      - traefik
networks:
  traefik:
    external: true
