version: "3.8"
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx.rule=Host(`nginx.minpeter.tech`)
      - traefik.http.routers.nginx.middlewares=traefik-auth
    networks:
      - traefik
networks:
  traefik:
    external: true
