version: "3.8"
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx.rule=Host(`nginx.minpeter.tech`,
        `ng.ctf.minpeter.tech`)
    networks:
      - traefik
networks:
  traefik:
    external: true
