version: '3.8'
services:
  wg-easy:
    image: weejewel/wg-easy
    container_name: wg-easy
    environment:
      - WG_HOST=114.201.7.126
    env_file:
      - .env
    volumes:
      - wg-easy:/etc/wireguard
    ports:
      - 51820:51820/udp
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.services.wg-easy.loadbalancer.server.port=51821
      - traefik.http.routers.wg-easy.rule=Host(`wg.minpeter.tech`, `vpn.minpeter.tech`)
      - traefik.http.routers.wg-easy.entrypoints=websecure
      - traefik.http.routers.wg-easy.tls.certresolver=myresolver
    networks:
      - traefik

networks:
  traefik:
    external: true

volumes:
  wg-easy:
    driver: local
