version: "3.8"
services:
  lucid-api:
    image: minpeter/lucid-backend:latest
    restart: unless-stopped
    volumes:
      - ./data.db:/data.db
    labels:
      - traefik.enable=true
      - traefik.http.routers.lucid.rule=Host(`lucid.minpeter.tech`)
    networks:
      - traefik
networks:
  traefik:
    external: true
