version: "3.8"
services:
  iplogger:
    container_name: ipLogger
    image: minpeter/iplogger
    restart: unless-stopped
    volumes:
      - iplogger-log:/log
    labels:
      - traefik.enable=true
      - traefik.http.routers.iplogger.rule=Host(`ip.minpeter.tech`, `ip.tmpf.me`)
      # enable http router
      - traefik.http.routers.iploggerhttp.rule=Host(`ip.minpeter.tech`, `ip.tmpf.me`)
      - traefik.http.routers.iploggerhttp.entrypoints=web
      - traefik.http.routers.iploggerhttp.priority=24
    networks:
      - traefik
networks:
  traefik:
    external: true
volumes:
  iplogger-log: null
