version: "3.8"
services:
  telos:
    image: ghcr.io/minpeter/telos:main
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - OAUTH_REDIRECT_URL=https://telos.minpeter.tech
      - GITHUB_CLIENT_ID=2fc583e09eaf299e94d4
      - GITHUB_CLIENT_SECRET=2949296e8af91f14ac19841aad765f4b5b540b9e
    labels:
      - traefik.enable=true
      - traefik.http.routers.telos-ctf.rule=Host(`telos.minpeter.tech`)
    networks:
      - traefik
networks:
  traefik:
    external: true
