version: "3"
services:
  # jenkins docker demon
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    environment:
      - TZ=Asia/Seuol
      - JAVA_OPTS=-Duser.timezone=Asia/Seuol

volumes:
  jenkins_home: