version: "3.8"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
    environment:
      TZ: Asia/Seoul
    env_file:
      - .env
    volumes:
      - etc-pihole:/etc/pihole
      - etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.services.pihole.loadbalancer.server.port=80
      - traefik.http.routers.pihole.rule=Host(`dns.minpeter.tech`) &&
        PathPrefix(`/admin`)
      - traefik.http.routers.pihole.entrypoints=websecure
    networks:
      - traefik
networks:
  traefik:
    external: true
volumes:
  etc-pihole: null
  etc-dnsmasq.d: null
